"""empty message

Revision ID: cf0f1792188d
Revises: f46290c0832a
Create Date: 2022-08-13 22:33:49.628623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0f1792188d'
down_revision = 'f46290c0832a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('upcoming_shows_num', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('past_shows__num', sa.Integer(), nullable=True))
    op.drop_column('Artist', 'upcoming_shows_count')
    op.drop_column('Artist', 'past_shows_count')
    op.add_column('Venue', sa.Column('upcoming_shows_num', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('past_shows_num', sa.Integer(), nullable=True))
    op.drop_column('Venue', 'upcoming_shows_count')
    op.drop_column('Venue', 'past_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'past_shows_num')
    op.drop_column('Venue', 'upcoming_shows_num')
    op.add_column('Artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'past_shows__num')
    op.drop_column('Artist', 'upcoming_shows_num')
    # ### end Alembic commands ###
